<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SecurityAwareness.Platform</RootNamespace>
    <AssemblyName>SecurityAwareness.Platform</AssemblyName>
    <UserSecretsId>securityawareness-platform</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1848;CA1873;CA1305;CA1861;CA1826;CA1827;NU1903;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityAwareness.Common\SecurityAwareness.Common.csproj" />
    <ProjectReference Include="..\SecurityAwareness.Infrastructure\SecurityAwareness.Infrastructure.csproj" />
    <ProjectReference Include="..\SecurityAwareness.Application\SecurityAwareness.Application.csproj" />
  </ItemGroup>

</Project>
